finale
Andrey-Mul/qa_paython_sprint_5 pull request #1
Opened 2023-11-06 12:35 UTC by Andrey-Mul

2023-11-07 17:43 UTC, kadirovgm requested changes

2023-11-07 17:43 UTC, kadirovgm commented on test.txt
нужно исправить: не нужные файлы не стоит мержить в общую ветку и отправлять на проверку :)

2023-11-07 17:43 UTC, kadirovgm commented on README.txt
> +
Можно лучше: Readme хорошее, но его обычно принято составлять в разметке Markdown и сохранять в формате .MD

2023-11-07 17:43 UTC, kadirovgm commented on README.txt
> +Локаторы:
нужно исправить: для чего тут описаны локаторы?

2023-11-07 17:43 UTC, kadirovgm commented on tests/conftest.py
> +    driver.get("https://stellarburgers.nomoreparties.site/")
Можно лучше: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-11-07 17:43 UTC, kadirovgm commented on tests/conftest.py
> +        browser.find_element(By.XPATH, "/html/body/div/div/main/section[2]/div/button").click()
нужно исправить: все локаторы держим в одном месте, например, в файле locators.py сгруппировав по экранам

класс с локаторами в файле `locators.py` лучше разделить на несколько: например `AuthPageLocators`, `MainPageLocators`
Сейчас это не критично, но в будущем это точно стоит сделать, так как таким образом ты не будешь импортить лишние локаторы в файл с тестами на экран авторизации. Т.е. у каждой страницы должен быть свой класс с локаторами.
    
    При таком подходе код станет лаконичнее, легко поддерживаемой. Ведь у экрана авторизации и у экрана главной могут быть свои NEXT_BUTTON например. Тогда можно будет легко оба обозвать именно так:
    `MainPageLocators.NEXT_BUTTON` и `AuthPageLocators.NEXT_BUTTON`

2023-11-07 17:43 UTC, kadirovgm commented on tests/conftest.py
> +def register_user(browser):
можно лучше: фикстура для регистрации наверное имеет место быть, но куда важнее иметь фикстуру для авторизации, которая будет использована в тестах, где она нужна, но явно авторизацию проверять не нужно

2023-11-07 17:43 UTC, kadirovgm commented on tests/conftest.py
> +def enter_on_main(browser):
нужно исправить: я бы переименовал это как функцию-фикстуру для авторизации

2023-11-07 17:43 UTC, kadirovgm commented on tests/follow_the_link.py
> +    email = "Andrey_mul_23@yandex.ru"
нужно исправить: тестовые данные давай выносить из кода тестов в data.py

2023-11-07 17:43 UTC, kadirovgm commented on tests/follow_the_link.py
> +    assert url == browser.current_url
нужно исправить: эта проверка не гарантирует, что тест успешный, наличие URL ничего не говорит даже о том, загрузилась страница или нет

Стоит добавить проверку наличия какого-либо ключевого элемента страницы, которая подтверждает, что авторизация успешна

править здесь и ниже в тестах

2023-11-07 17:43 UTC, kadirovgm commented on tests/follow_the_link.py
> +
можно лучше: я бы рекомендовал оставлять комменты в формате "докстринг" перед каждым тестом, в реальных проектах обычно так делают и это помогает понять о чем тест

2023-11-07 17:43 UTC, kadirovgm commented on tests/test_enter.py
> +    assert url == result
можно лучше: assert url == browser.current_url

Но, повторюсь, проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-11-08 00:07 UTC, Andrey-Mul commented on test.txt
С этим не смог справиться, перепробовал все что знал. И в игнор его добавлял и git rm --cached test.txt и прочее, что смог найти. Но он все-ровно весит.

2023-11-08 00:07 UTC, Andrey-Mul commented on README.txt
> +
Исправил

2023-11-08 00:07 UTC, Andrey-Mul commented on README.txt
> +Локаторы:
Исправил

2023-11-08 00:08 UTC, Andrey-Mul commented on tests/conftest.py
> +    driver.get("https://stellarburgers.nomoreparties.site/")
Исправил. 
Правда тут или я что-то прослушал или мы эту тему только начали проходить про POM

2023-11-08 00:09 UTC, Andrey-Mul commented on tests/conftest.py
> +        browser.find_element(By.XPATH, "/html/body/div/div/main/section[2]/div/button").click()
Исправил. Работать с кодом стало удобнее

2023-11-08 00:09 UTC, Andrey-Mul commented on tests/conftest.py
> +def enter_on_main(browser):
Исправил

2023-11-08 00:09 UTC, Andrey-Mul commented on tests/follow_the_link.py
> +    email = "Andrey_mul_23@yandex.ru"
Исправил

2023-11-08 00:10 UTC, Andrey-Mul commented on tests/follow_the_link.py
> +    assert url == browser.current_url
Исправил, переделал проверки во всех тестах с _url проверками _

2023-11-08 00:10 UTC, Andrey-Mul commented on tests/follow_the_link.py
> +
Добавил.

2023-11-08 00:10 UTC, Andrey-Mul commented on tests/test_enter.py
> +    assert url == result
Исправил

2023-11-08 19:41 UTC, kadirovgm commented on test.txt
а удалить файл?

2023-11-08 19:42 UTC, kadirovgm commented on tests/conftest.py
> +    driver.get("https://stellarburgers.nomoreparties.site/")
POM тут не причем, но да его вы далее пройдете

возможно вы этот коммент и не проходили, я просто даю свои советы по организации кода :)

2023-11-08 19:43 UTC, kadirovgm approved these changes

2023-11-08 19:43 UTC, kadirovgm commented on tests/follow_the_link.py
> +    Тест перехода по клику на «Личный кабинет».
отлично!

2023-11-08 19:43 UTC, kadirovgm commented on tests/locators.py
> +
молодец!

2023-11-08 20:01 UTC, merged